---
title: "Moralized Language Predicts Hate Speech (Supplements)"
author: KS
date: '`r format(Sys.Date(), "%B %d, %Y")`'
header-includes:
   - \usepackage{dcolumn}
   - \usepackage{booktabs}
   - \usepackage{float}
   - \usepackage{longtable}
   - \usepackage{multirow}
   - \usepackage{siunitx}
output:
  pdf_document:
    toc: yes
    keep_tex: no
    number_sections: yes

---

```{r library, include=FALSE}
library(tidyverse)
library(lme4)
library(glmmTMB)
library(texreg)
library(xtable)
library(broom)
library(lubridate)
library(wesanderson)
library(broom)
library(broom.mixed)
library(brms)
library(car)
library(tidymodels)
library(furrr)

options(xtable.comment = FALSE)
options(width = 80)

plan(multisession, workers = parallel::detectCores() / 2)

source("utils.R")
options(scipen = 999)
```

```{r Set paths, include = FALSE}
inputPath <- "../Data/"
graphPath <- "../Data/Graphs/"
```

# Functions
```{r scale and add factors}
factorize_df <- function(df) {
  df <- df %>%
    mutate(
      UserID = factor(UserID),
      SourceHate = factor(SourceHate)
    ) %>%
    mutate(SourceHate = relevel(SourceHate, "regular"))
  
  return(df)
}
```

# Variable Definitions

```{r replacement dict}
vnames_list <- c(
  "(Intercept)" = "Intercept",
  "TextComplexity" = "Text Complexity",
  "MoralWords" = "Moral Words",
  "MoralWordsProp" = "Moral Words",
  "MoralBinaryTRUE" = "Moral Words (binary)",
  "MoralEmotionalWords" = "Moral-Emotional Words",
  "MoralEmotionalWordsProp" = "Moral-Emotional Words",
  "MoralEmotionalBinaryTRUE" = "Moral-Emotional Words (binary)",
  "EmotionalWords" = "Emotional Words",
  "EmotionalWordsProp" = "Emotional Words",
  "WordCount" = "Word Count",
  "EmotionalPositive" = "Positive Emotional Words",
  "EmotionalNegative" = "Negative Emotional Words",
  "QuoteTRUE" = "Quote (binary)",
  "MediaAttachedTRUE" = "Media Attached (binary)",
  "WordCount" = "Word Count",
  "SourceHatehate" = "Hateful Source (binary)",
  "MoralWords:WordCount" = "Moral Words x Word Count",
  "MoralEmotionalWords:WordCount" = "Moral-Emotional Words x Word Count",
  "XYZCount" = "XYZ Count"
)
```

# Load Data

```{r load preprocessed data}
df_regression_politicians <- read_csv(paste0(inputPath, "df_politicians.csv")) %>% factorize_df()
df_regression_newspeople <- read_csv(paste0(inputPath, "df_newspeople.csv")) %>% factorize_df()
df_regression_activists <- read_csv(paste0(inputPath, "df_activists.csv")) %>% factorize_df()

# List for use in regressions
df_list <- list(df_regression_politicians, df_regression_newspeople, df_regression_activists)
names(df_list) <- c("Politicians", "Newspeople", "Activists")
```
<!--
# Regression Analysis 

## Regression with Interactions

```{r Regression Interactions}
regressions_covariates <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + MoralWords * WordCount + MoralEmotionalWords * WordCount + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

texreg(regressions_covariates, digits = 3)
map(regressions_covariates, get_cis)
```

## Generalized vs. directed hate speech

```{r}
# 2PP
regressions_2pp <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HRepliesDirected, Replies - HRepliesDirected) ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

# 3PP
regressions_3pp <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HRepliesGeneralized, Replies - HRepliesGeneralized) ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

texreg(c(regressions_2pp, regressions_3pp), digits = 3)
map(c(regressions_2pp, regressions_3pp), get_cis)
```

## Regression controlling for hate speech in source tweets

```{r regression source hate}
regressions_source <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + Quote + SourceHate + EmotionalWords + MoralWords + MoralEmotionalWords + WordCount + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

texreg(regressions_source, digits = 3)
map(regressions_source, get_cis)
```

## Beta regressions
```{r zoiRegression beta}
regressions_beta_full <- df_list %>% future_map(., function(x) {
  model <- brm(bf(ProportionOfHate ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + (1 | UserID),
    phi ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + (1 | UserID),
    zoi ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + (1 | UserID),
    coi ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + (1 | UserID),
    family = zero_one_inflated_beta()
  ),
  data = x,
  cores = 7,
  seed = TRUE
  )
})

texreg(c(
  extract(regressions_beta_full$Politicians, include.random = F),
  extract(regressions_beta_full$Newspeople, include.random = F),
  extract(regressions_beta_full$Activists, include.random = F)
), digits = 3)
```

## Regression with proportions instead of frequencies

```{r regression proportions}
add_proportions <- function(df) {
  df <- df %>%
    mutate(
      MoralWordsProp = MoralWords / WordCount,
      MoralEmotionalWordsProp = MoralEmotionalWords / WordCount,
      EmotionalWordsProp = EmotionalWords / WordCount
    )
  return(df)
}

regressions_proportions <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + MoralWordsProp + MoralEmotionalWordsProp + EmotionalWordsProp + WordCount + Quote + (1 | UserID),
    data = add_proportions(x),
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

texreg(regressions_proportions, digits = 3)
map(regressions_proportions, get_cis)
```

## Regressions with binary variables for moral and moral-emotional words

```{r regression moral_bin}
add_binary <- function(df) {
  df <- df %>% mutate(
    MoralBinary = ifelse(MoralWords > 0, TRUE, FALSE),
    MoralEmotionalBinary = ifelse(MoralEmotionalWords > 0, TRUE, FALSE)
  )
}

regressions_moralbin <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + MoralBinary + MoralEmotionalBinary + EmotionalWords + WordCount + Quote + (1 | UserID),
    data = add_binary(x),
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

texreg(regressions_moralbin, digits = 3)
map(regressions_moralbin, get_cis)
```

## Regressions with distinctly positive and negative emotional words

```{r regression_distinct}
regressions_distinct <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalPositive + EmotionalNegative + WordCount + Quote + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

texreg(regressions_distinct, digits = 3)
map(regressions_distinct, get_cis)
```

## Regressions with the number of retweets

```{r regression_retweets}
scale_df <- function(df) {
  df <- df %>%
    mutate(
      TextComplexityZ = scale(TextComplexity),
      MoralWordsZ = scale(MoralWords),
      MoralEmotionalWordsZ = scale(MoralEmotionalWords),
      EmotionalWordsZ = scale(EmotionalWords),
      WordCountZ = scale(WordCount),
      RetweetCountZ = scale(RetweetCount),
      LikeCountZ = scale(LikeCount)
    ) 
}

regressions_retweet <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexityZ + MoralWordsZ + MoralEmotionalWordsZ + EmotionalWordsZ + WordCountZ + Quote + RetweetCountZ + (1 | UserID),
    data = scale_df(x),
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

texreg(regressions_retweet, digits = 3)
map(regressions_retweet, get_cis)
```

## Regressions with the number of likes

```{r regression_likes}
regressions_likes <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexityZ + MoralWordsZ + MoralEmotionalWordsZ + EmotionalWordsZ + WordCountZ + Quote + LikeCountZ + (1 | UserID),
    data = scale_df(x),
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

texreg(regressions_likes, digits = 3)
map(regressions_likes, get_cis)
```

## Regressions with XYZ-Count

```{r XYZ Regression}
regressions_xyz <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + XYZCount + EmotionalWords + WordCount + Quote + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

regressions_main <- df_list %>% future_map(., function(x) {
  model <- glmer(cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    nAGQ = 1,
    glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8))
  )
})

texreg(c(regressions_xyz$Politicians, regressions_main$Politicians, regressions_xyz$Newspeople, regressions_main$Newspeople, regressions_xyz$Activists, regressions_main$Activists), digits = 3)

# VIF
map(regressions_main, vif)

# CIs
map(regressions_xyz, get_cis)
```

# Out-of-Sample Evaluation

```{r predict tidymodels glm}
evaluate_models_glm <- function(df, metric = yardstick::rsq) {
  df <- df %>% mutate(Replies = frequency_weights(Replies))
  folds <- vfold_cv(df, v = 10)

  mod_glm <- linear_reg() %>%
    set_engine("glm",
      family = stats::binomial(link = "logit")
    ) %>%
    translate()

  dep_var <- "ProportionOfHate"
  author_vars <- c("Followers", "Followees", "AccountAge", "Verified")
  content_vars <- c("WordCount", "TextComplexity", "EmotionalWords", "Quote", "MediaAttached")
  xyz_vars <- c("XYZCount")
  moral_vars <- c("MoralWords", "MoralEmotionalWords")
  spec_list <- list(author_vars, c(author_vars, content_vars), c(author_vars, content_vars, xyz_vars), c(author_vars, content_vars, moral_vars))

  workflow_list <- spec_list %>% future_map(., function(var) {
    workflow() %>%
      add_variables(outcomes = dep_var, predictors = all_of(var)) %>%
      add_model(mod_glm, formula = make_formula(dep_var, c(var), c())) %>%
      add_case_weights(Replies)
  })
  metrics <- workflow_list %>%
    future_map(., function(x) {
      fit_resamples(x, folds, metrics = metric_set(metric)) %>%
        collect_metrics() %>%
        pull(mean)
    })

  return(metrics)
}

r2_results <- map(df_list, evaluate_models_glm)

tibble(
  Model = c("Author", "Content", "XYZ", "Moral"),
  Politicians = r2_results$Politicians %>% unlist(),
  Newspeople = r2_results$News %>% unlist(),
  Activists = r2_results$Activists %>% unlist()
) %>% arrange(desc(Politicians))
```

# Out-of-Sample Evaluation (AUC)

```{r predict tidymodels glm auc, warning = FALSE, message=FALSE}
evaluate_models_glm_auc <- function(df, metric = yardstick::roc_auc) {
  df <- df %>%
    filter(Replies > 10) %>%
    mutate(
      ExtremelyHateful = if_else(
        ProportionOfHate > quantile(ProportionOfHate, probs = 0.75), TRUE, FALSE
      ),
      Replies = frequency_weights(Replies),
      ExtremelyHateful = factor(ExtremelyHateful),
      ExtremelyHateful = relevel(ExtremelyHateful, "TRUE")
    )

  folds <- vfold_cv(df, v = 10)

  mod_glm <- logistic_reg() %>%
    set_engine("glm",
      family = stats::binomial(link = "logit")
    ) %>%
    translate()

  dep_var <- "ExtremelyHateful"
  author_vars <- c("Followers", "Followees", "AccountAge", "Verified")
  content_vars <- c("WordCount", "TextComplexity", "EmotionalWords", "Quote", "MediaAttached")
  xyz_vars <- c("XYZCount")
  moral_vars <- c("MoralWords", "MoralEmotionalWords")
  spec_list <- list(
    author_vars,
    c(author_vars, content_vars),
    c(author_vars, content_vars, xyz_vars),
    c(author_vars, content_vars, moral_vars)
  )

  workflow_list <- spec_list %>% future_map(., function(var) {
    workflow() %>%
      add_variables(outcomes = dep_var, predictors = all_of(var)) %>%
      add_model(mod_glm, formula = make_formula(dep_var, c(var), c()))
  })
  metrics <- workflow_list %>%
    future_map(., function(x) {
      fit_resamples(x,
        folds,
        metrics = metric_set(metric),
        control = control_resamples(save_pred = TRUE)
      )
    })

  return(metrics)
}

plot_roc <- function(df) {
  df %>%
    map2(., specifications_list, function(x, y) {
      collect_predictions(x) %>%
        roc_curve(ExtremelyHateful, .pred_TRUE) %>%
        mutate(Model = y)
    }) %>%
    bind_rows() %>%
    ggplot(aes(x = 1 - specificity, y = sensitivity, color = Model)) +
    geom_path() +
    geom_abline(lty = 3) +
    theme_bw() +
    theme(
      legend.position = c(0.7, 0.3),
      legend.title = element_blank(),
      legend.direction = "vertical",
      axis.text.x = element_text(colour = "black"),
      axis.text.y = element_text(colour = "black")
    ) +
    xlab("False Positive Rate") +
    ylab("True Positive Rate") +
    scale_color_manual(values = c(
      wesanderson::wes_palette("FantasticFox1")[1],
      wesanderson::wes_palette("FantasticFox1")[2],
      wesanderson::wes_palette("FantasticFox1")[3],
      wesanderson::wes_palette("FantasticFox1")[5]
    ))
}

get_auc <- function(df) {
  df %>%
    map2(., specifications_list, function(x, y) {
      collect_metrics(x) %>%
        select(mean) %>%
        mutate(Model = y)
    }) %>%
    bind_rows()
}

specifications_list <- c("AF", "AF + CF", "AF + CF + XYZ", "AF + CF + MF")
roc_results <- map(df_list, evaluate_models_glm_auc)
roc_results %>% map(., get_auc)
roc_results %>% map(., plot_roc)
```
-->
<!-- This is the example stuff
# Regression Analysis 

## Regression with Interactions

```{r}
# Sample data for demonstration
set.seed(123)
df_list_sample <- df_list %>% map(., function(x) {
  x %>% slice_sample(n = min(750, nrow(x)))
})

regressions_covariates <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting model for:", name, "\n")
  cat("Sample size:", nrow(x), "rows\n")
  
  model <- glmer(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + MoralWords * WordCount + MoralEmotionalWords * WordCount + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

texreg(regressions_covariates, digits = 3)
map(regressions_covariates, get_cis)
```

## Generalized vs. directed hate speech

```{r}
# 2PP
regressions_2pp <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting 2PP model for:", name, "\n")
  
  model <- glmer(
    formula = cbind(HRepliesDirected, Replies - HRepliesDirected) ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

# 3PP
regressions_3pp <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting 3PP model for:", name, "\n")
  
  model <- glmer(
    formula = cbind(HRepliesGeneralized, Replies - HRepliesGeneralized) ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

texreg(c(regressions_2pp, regressions_3pp), digits = 3)
map(c(regressions_2pp, regressions_3pp), get_cis)
```

## Regression controlling for hate speech in source tweets

```{r}
regressions_source <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting source hate model for:", name, "\n")
  
  model <- glmer(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + Quote + SourceHate + EmotionalWords + MoralWords + MoralEmotionalWords + WordCount + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

texreg(regressions_source, digits = 3)
map(regressions_source, get_cis)
```

## Regression with proportions instead of frequencies

```{r}
add_proportions <- function(df) {
  df <- df %>%
    mutate(
      MoralWordsProp = MoralWords / WordCount,
      MoralEmotionalWordsProp = MoralEmotionalWords / WordCount,
      EmotionalWordsProp = EmotionalWords / WordCount
    )
  return(df)
}

regressions_proportions <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting proportions model for:", name, "\n")
  
  model <- glmer(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + MoralWordsProp + MoralEmotionalWordsProp + EmotionalWordsProp + WordCount + Quote + (1 | UserID),
    data = add_proportions(x),
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

texreg(regressions_proportions, digits = 3)
map(regressions_proportions, get_cis)
```

## Regressions with binary variables for moral and moral-emotional words

```{r}
add_binary <- function(df) {
  df <- df %>% mutate(
    MoralBinary = ifelse(MoralWords > 0, TRUE, FALSE),
    MoralEmotionalBinary = ifelse(MoralEmotionalWords > 0, TRUE, FALSE)
  )
}

regressions_moralbin <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting binary model for:", name, "\n")
  
  model <- glmer(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + MoralBinary + MoralEmotionalBinary + EmotionalWords + WordCount + Quote + (1 | UserID),
    data = add_binary(x),
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

texreg(regressions_moralbin, digits = 3)
map(regressions_moralbin, get_cis)
```

## Regressions with distinctly positive and negative emotional words

```{r}
regressions_distinct <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting distinct emotions model for:", name, "\n")
  
  model <- glmer(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalPositive + EmotionalNegative + WordCount + Quote + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

texreg(regressions_distinct, digits = 3)
map(regressions_distinct, get_cis)
```

## Regressions with the number of retweets

```{r}
scale_df <- function(df) {
  df <- df %>%
    mutate(
      TextComplexityZ = scale(TextComplexity),
      MoralWordsZ = scale(MoralWords),
      MoralEmotionalWordsZ = scale(MoralEmotionalWords),
      EmotionalWordsZ = scale(EmotionalWords),
      WordCountZ = scale(WordCount),
      RetweetCountZ = scale(RetweetCount),
      LikeCountZ = scale(LikeCount)
    ) 
}

regressions_retweet <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting retweet model for:", name, "\n")
  
  model <- glmer(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexityZ + MoralWordsZ + MoralEmotionalWordsZ + EmotionalWordsZ + WordCountZ + Quote + RetweetCountZ + (1 | UserID),
    data = scale_df(x),
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

texreg(regressions_retweet, digits = 3)
map(regressions_retweet, get_cis)
```

## Regressions with the number of likes

```{r}
regressions_likes <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting likes model for:", name, "\n")
  
  model <- glmer(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexityZ + MoralWordsZ + MoralEmotionalWordsZ + EmotionalWordsZ + WordCountZ + Quote + LikeCountZ + (1 | UserID),
    data = scale_df(x),
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

texreg(regressions_likes, digits = 3)
map(regressions_likes, get_cis)
```

## Regressions with XYZ-Count

```{r}
regressions_xyz <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting XYZ model for:", name, "\n")
  
  model <- glmer(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + XYZCount + EmotionalWords + WordCount + Quote + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

regressions_main <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Starting main model for:", name, "\n")
  
  model <- glmer(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + Quote + (1 | UserID),
    data = x,
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e8)),
    nAGQ = 1,
    subset = NULL,
    weights = NULL,
    na.action = na.omit,
    offset = NULL,
    contrasts = NULL,
    mustart = NULL,
    etastart = NULL
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

texreg(c(regressions_xyz$Politicians, regressions_main$Politicians, regressions_xyz$Newspeople, regressions_main$Newspeople, regressions_xyz$Activists, regressions_main$Activists), digits = 3)

# VIF
map(regressions_main, vif)

# CIs
map(regressions_xyz, get_cis)
```
-->





# CODE DEVELOPMENT CHECK 3 (03/01/2026)
```{r}
# ============================================
# ALTERNATIVE MODEL SPECIFICATIONS - SUPPLEMENTS
# Testing four different modeling approaches
# ============================================

set.seed(123)  # For reproducibility
sample_size <- 750  # Consistent with your supplement demonstrations

cat("=" , rep("=", 50), "\n", sep = "")
cat("RUNNING ALTERNATIVE MODEL SPECIFICATIONS (SUPPLEMENTS)\n")
cat("Sample size:", sample_size, "rows per dataset\n")
cat("Models: 1. Zero-Inflated Beta-Binomial\n")
cat("        2. Hurdle Model\n")
cat("        3. Generalized Additive Mixed Model (GAMM)\n")
cat("        4. Mixed Effects Random Forest\n")
cat("=" , rep("=", 50), "\n\n", sep = "")

# Create sampled datasets
df_list_sample <- df_list %>% map(., function(x) {
  x %>% slice_sample(n = min(sample_size, nrow(x)))
})

#===============================================================================
# MODEL 1: ZERO-INFLATED BETA-BINOMIAL MIXED MODEL
#===============================================================================

library(glmmTMB)

cat("\n" , rep("=", 50), "\n", sep = "")
cat("MODEL 1: Zero-Inflated Beta-Binomial\n")
cat(rep("=", 50), "\n", sep = "")

## 1.1 Main specification
zibb_main <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Fitting ZIBB main model for:", name, "\n")
  
  model <- glmmTMB(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + 
      MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + 
      Quote + (1 | UserID),
    ziformula = ~ MediaAttached + MoralWords + MoralEmotionalWords + (1 | UserID),
    data = x,
    family = betabinomial(link = "logit"),
    control = glmmTMBControl(optCtrl = list(iter.max = 1e5, eval.max = 1e5))
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

## 1.2 With proportions instead of frequencies
add_proportions <- function(df) {
  df %>% mutate(
    MoralWordsProp = MoralWords / WordCount,
    MoralEmotionalWordsProp = MoralEmotionalWords / WordCount,
    EmotionalWordsProp = EmotionalWords / WordCount
  )
}

zibb_proportions <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Fitting ZIBB with proportions for:", name, "\n")
  
  model <- glmmTMB(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + 
      MoralWordsProp + MoralEmotionalWordsProp + EmotionalWordsProp + WordCount + 
      Quote + (1 | UserID),
    ziformula = ~ MediaAttached + MoralWordsProp + MoralEmotionalWordsProp + (1 | UserID),
    data = add_proportions(x),
    family = betabinomial(link = "logit"),
    control = glmmTMBControl(optCtrl = list(iter.max = 1e5, eval.max = 1e5))
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

## 1.3 With binary indicators
add_binary <- function(df) {
  df %>% mutate(
    MoralBinary = ifelse(MoralWords > 0, TRUE, FALSE),
    MoralEmotionalBinary = ifelse(MoralEmotionalWords > 0, TRUE, FALSE)
  )
}

zibb_binary <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Fitting ZIBB with binary indicators for:", name, "\n")
  
  model <- glmmTMB(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + 
      MoralBinary + MoralEmotionalBinary + EmotionalWords + WordCount + 
      Quote + (1 | UserID),
    ziformula = ~ MediaAttached + MoralBinary + MoralEmotionalBinary + (1 | UserID),
    data = add_binary(x),
    family = betabinomial(link = "logit"),
    control = glmmTMBControl(optCtrl = list(iter.max = 1e5, eval.max = 1e5))
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

## 1.4 With interactions
zibb_interactions <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Fitting ZIBB with interactions for:", name, "\n")
  
  model <- glmmTMB(
    formula = cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + 
      MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + 
      Quote + MoralWords:WordCount + MoralEmotionalWords:WordCount + (1 | UserID),
    ziformula = ~ MediaAttached + MoralWords + MoralEmotionalWords + (1 | UserID),
    data = x,
    family = betabinomial(link = "logit"),
    control = glmmTMBControl(optCtrl = list(iter.max = 1e5, eval.max = 1e5))
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

#===============================================================================
# MODEL 2: GENERALIZED ADDITIVE MIXED MODEL (GAMM)
#===============================================================================

cat("\n" , rep("=", 50), "\n", sep = "")
cat("MODEL 3: Generalized Additive Mixed Model (GAMM)\n")
cat(rep("=", 50), "\n", sep = "")

library(mgcv)

## 3.1 Main specification with smooths
gamm_main <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Fitting GAMM main model for:", name, "\n")
  
  model <- gam(
    formula = cbind(HReplies, Replies - HReplies) ~ 
      MediaAttached + 
      s(TextComplexity, k = 5) +
      s(MoralWords, k = 5) +
      s(MoralEmotionalWords, k = 5) +
      s(EmotionalWords, k = 5) +
      s(WordCount, k = 5) +
      Quote +
      s(UserID, bs = "re"),
    data = x,
    family = binomial(link = "logit"),
    method = "REML"
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

## 3.2 With tensor product interactions (for non-linear interactions)
gamm_tensor <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Fitting GAMM with tensor interactions for:", name, "\n")
  
  # Need to ensure UserID is factor
  x <- x %>% mutate(UserID = factor(UserID))
  
  model <- gam(
    formula = cbind(HReplies, Replies - HReplies) ~ 
      MediaAttached + 
      s(TextComplexity, k = 5) +
      te(MoralWords, WordCount, k = 4) +              # Tensor interaction
      te(MoralEmotionalWords, WordCount, k = 4) +      # Tensor interaction
      s(EmotionalWords, k = 5) +
      Quote +
      s(UserID, bs = "re"),
    data = x,
    family = binomial(link = "logit"),
    method = "REML"
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

#===============================================================================
# MODEL 3: MIXED EFFECTS RANDOM FOREST
#===============================================================================

cat("\n" , rep("=", 50), "\n", sep = "")
cat("MODEL 4: Mixed Effects Random Forest\n")
cat(rep("=", 50), "\n", sep = "")

if(!require(MixRF)) {
  install.packages("MixRF")
}
library(MixRF)
library(ranger)

## 4.1 Main specification
merf_main <- df_list_sample %>% imap(., function(x, name) {
  cat("\n----------------------------------------\n")
  cat("Fitting MERF main model for:", name, "\n")
  
  x_merf <- x %>%
    mutate(
      UserID = as.numeric(factor(UserID)),
      weight = Replies
    )
  
  X <- x_merf %>% select(MediaAttached, TextComplexity, MoralWords, 
                         MoralEmotionalWords, EmotionalWords, WordCount, Quote)
  
  set.seed(123)
  model <- MixRF(
    Y = x_merf$ProportionOfHate,
    X = X,
    random = "(1 | UserID)",
    data = x_merf,
    weight = x_merf$weight,
    ErrorTolerance = 0.001,
    MaxIterations = 10,
    num.trees = 500,
    mtry = floor(ncol(X) / 3)
  )
  
  cat("✓ Completed:", name, "\n")
  return(model)
})

## 4.2 Variable importance extraction
merf_importance <- map(merf_main, function(model) {
  if(!is.null(model$forest)) {
    importance <- ranger::importance(model$forest)
    data.frame(
      variable = names(importance),
      importance = as.numeric(importance)
    ) %>%
      arrange(desc(importance))
  } else {
    NULL
  }
})

# Print importance
cat("\nVariable Importance from Random Forests:\n")
map2(merf_importance, names(merf_importance), function(imp, name) {
  cat("\n", name, ":\n", sep = "")
  if(!is.null(imp)) {
    print(head(imp, 5))
  }
})

#===============================================================================
# OUT-OF-SAMPLE PREDICTION COMPARISON
#===============================================================================

cat("\n" , rep("=", 50), "\n", sep = "")
cat("OUT-OF-SAMPLE PREDICTION COMPARISON\n")
cat(rep("=", 50), "\n", sep = "")

# Function to calculate prediction error for each model type
compare_predictions <- function(df, train_prop = 0.7) {
  set.seed(456)
  
  # Split data
  n <- nrow(df)
  train_idx <- sample(1:n, size = floor(n * train_prop))
  train <- df[train_idx, ]
  test <- df[-train_idx, ]
  
  results <- list()
  
  # 1. Original GLMM (for baseline)
  glmm_model <- glmer(
    cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + 
      MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + 
      Quote + (1 | UserID),
    data = train,
    family = binomial(link = "logit"),
    control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5))
  )
  
  # 2. ZIBB
  zibb_model <- glmmTMB(
    cbind(HReplies, Replies - HReplies) ~ MediaAttached + TextComplexity + 
      MoralWords + MoralEmotionalWords + EmotionalWords + WordCount + 
      Quote + (1 | UserID),
    ziformula = ~ MediaAttached + MoralWords + MoralEmotionalWords + (1 | UserID),
    data = train,
    family = betabinomial(link = "logit")
  )
  
  # 3. GAMM
  gamm_model <- gam(
    cbind(HReplies, Replies - HReplies) ~ 
      MediaAttached + 
      s(MoralWords, k = 4) +
      s(MoralEmotionalWords, k = 4) +
      s(EmotionalWords, k = 4) +
      TextComplexity + WordCount + Quote +
      s(UserID, bs = "re"),
    data = train,
    family = binomial(link = "logit"),
    method = "REML"
  )
  
  # Predictions on test set
  test_pred <- test %>%
    mutate(
      # GLMM predictions
      pred_glmm = predict(glmm_model, newdata = ., type = "response", 
                          allow.new.levels = TRUE),
      
      # ZIBB predictions (need to extract conditional part)
      pred_zibb = predict(zibb_model, newdata = ., type = "response", 
                          allow.new.levels = TRUE),
      
      # GAM predictions
      pred_gamm = predict(gamm_model, newdata = ., type = "response")
    )
  
  # Calculate MSE for each model
  actual_prop <- test_pred$HReplies / test_pred$Replies
  
  mse <- list(
    GLMM = mean((actual_prop - test_pred$pred_glmm)^2, na.rm = TRUE),
    ZIBB = mean((actual_prop - test_pred$pred_zibb)^2, na.rm = TRUE),
    GAMM = mean((actual_prop - test_pred$pred_gamm)^2, na.rm = TRUE)
  )
  
  return(mse)
}

# Run comparison for each dataset
pred_comparison <- map(df_list_sample, function(df) {
  tryCatch({
    compare_predictions(df)
  }, error = function(e) {
    cat("Error in prediction comparison:", e$message, "\n")
    return(NULL)
  })
})

# Print results
cat("\nPrediction MSE (lower is better):\n")
map2(pred_comparison, names(pred_comparison), function(comp, name) {
  if(!is.null(comp)) {
    cat("\n", name, ":\n", sep = "")
    cat("  GLMM:", round(comp$GLMM, 6), "\n")
    cat("  ZIBB:", round(comp$ZIBB, 6), "\n")
    cat("  GAMM:", round(comp$GAMM, 6), "\n")
    
    # Find best model
    best <- names(comp)[which.min(unlist(comp))]
    cat("  Best:", best, "\n")
  }
})

#===============================================================================
# MODEL COMPARISON SUMMARY
#===============================================================================

cat("\n" , rep("=", 50), "\n", sep = "")
cat("SUMMARY: WHAT EACH MODEL TELLS US\n")
cat(rep("=", 50), "\n", sep = "")

cat("
1. Zero-Inflated Beta-Binomial:
   - Separates 'zero hate' process from 'how much hate' process
   - Can tell us: Does moralized language primarily trigger ANY hate,
     or does it increase the INTENSITY of hate?
   
2. Hurdle Model:
   - Similar to ZIBB but assumes all zeros are structural
   - Can tell us: Is there a threshold effect for moralized language?

3. Generalized Additive Mixed Model:
   - Allows non-linear relationships
   - Can tell us: Is the effect of moral words linear, or does it
     plateau/diminish after a certain point?

4. Mixed Effects Random Forest:
   - Captures complex interactions automatically
   - Can tell us: What combinations of variables most strongly predict hate?
     (e.g., MoralWords + Political Affiliation + WordCount)
")

cat("\n" , rep("=", 50), "\n", sep = "")
cat("ALTERNATIVE MODELS COMPLETE\n")
cat(rep("=", 50), "\n", sep = "")
```

